### PR TITLE
compiles now, and I took the "sell the whole inventory" functionality…

### PR DESCRIPTION
**Pull request by bshuler**
…, because that breaks our server rules. (EMC)

### CODE REVIEW

**Comment by bshuler** [comment]
BTW, I love your mod. Wouldn't mind collaborating some time.

**Comment by gbl** [comment]
Not sure why you had problems compiling, the following sequence of commands works for me:

```
git clone git@github.com:gbl/EasierVillagerTrading.git     # or https://.... in your case probably
cd EasierVillagerTrading/
git checkout -b fabric
git branch --set-upstream-to=origin/fabric fabric
git pull
/path/to/gradlew build   # where gradlew wraps version 4.10.2
```

I won't merge the pull request, because that'd take out the functionality for everybody else who's not playing on EMC. But I'd be happy to merge some code that checks if the player is playing on EMC, and disables the sell whole inventory feature in that case. I had something like this in my EMC Shop Locator mod where I was checking the hash of the server icon - that was in 1.12 though so would need some rewriting.

**Comment by gbl** [comment]
Oh, and, as to your changes to the gradle files - I switched over to having version info in a separate git submodule, which I can use for all my mods, beginning with 1.15. EVT 1.14 works with 1.15 as well, but the 1.16 branch of the mod uses the new system already, which is why I won't do much about the 1.14 branch of it any more.

**Comment by bshuler** [comment]
Many thanks. I am learning a good bit by reviewing your code. I am interested in seeing how the EMC portion looks.

**Comment by bshuler** [comment]
Following the same steps, I get:

bshuler@Omen:/mnt/c/Users/BertS/code/freshtest$ git clone https://github.com/gbl/EasierVillagerTrading.git
Cloning into 'EasierVillagerTrading'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 407 (delta 28), reused 82 (delta 24), pack-reused 314
Receiving objects: 100% (407/407), 219.62 KiB | 3.99 MiB/s, done.
Resolving deltas: 100% (105/105), done.
bshuler@Omen:/mnt/c/Users/BertS/code/freshtest$ cd EasierVillagerTrading/
bshuler@Omen:/mnt/c/Users/BertS/code/freshtest/EasierVillagerTrading$ git checkout -b fabric
Switched to a new branch 'fabric'
bshuler@Omen:/mnt/c/Users/BertS/code/freshtest/EasierVillagerTrading$ git branch --set-upstream-to=origin/fabric fabric
Branch 'fabric' set up to track remote branch 'fabric' from 'origin'.
bshuler@Omen:/mnt/c/Users/BertS/code/freshtest/EasierVillagerTrading$ git pull
Updating bad87a2..80c265a
Fast-forward
 .gitignore                                                                  |   1 +
 build.gradle                                                                |  89 ++++--------
 settings.gradle                                                             |  10 ++
 src/main/java/de/guntram/mcmod/debug/NBTdump.java                           |  40 ++++++
 src/main/java/de/guntram/mcmod/easiervillagertrading/AutoTrade.java         |  14 ++
 src/main/java/de/guntram/mcmod/easiervillagertrading/BetterGuiMerchant.java | 272 ++++++++----------------------------
 .../java/de/guntram/mcmod/easiervillagertrading/ConfigurationHandler.java   |  64 ---------
 .../java/de/guntram/mcmod/easiervillagertrading/EasierVillagerTrading.java  |  33 +----
 src/main/java/de/guntram/mcmod/easiervillagertrading/GuiConfig.java         |  16 ---
 src/main/java/de/guntram/mcmod/easiervillagertrading/GuiFactory.java        |  28 ----
 .../java/de/guntram/mcmod/easiervillagertrading/OpenTradeEventHandler.java  |  27 ----
 .../de/guntram/mcmod/easiervillagertrading/mixins/GuiMerchantMixin.java     |  29 ++++
 .../de/guntram/mcmod/easiervillagertrading/mixins/MerchantScreenMixin.java  |  40 ++++++
 src/main/resources/assets/easiervillagertrading/lang/en_US.lang             |   3 +
 src/main/resources/assets/easiervillagertrading/lang/en_us.json             |   5 +
 src/main/resources/fabric.mod.json                                          |  31 ++++
 src/main/resources/logo.png                                                 | Bin 0 -> 62839 bytes
 src/main/resources/mcmod.info                                               |  16 ---
 src/main/resources/mixins.easiervillagertrading.json                        |  12 ++
 src/main/resources/pack.mcmeta                                              |   6 +
 src/main/resources/pack.png                                                 | Bin 0 -> 15849 bytes
 21 files changed, 282 insertions(+), 454 deletions(-)
 create mode 100644 settings.gradle
 create mode 100644 src/main/java/de/guntram/mcmod/debug/NBTdump.java
 create mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/AutoTrade.java
 delete mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/ConfigurationHandler.java
 delete mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/GuiConfig.java
 delete mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/GuiFactory.java
 delete mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/OpenTradeEventHandler.java
 create mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/mixins/GuiMerchantMixin.java
 create mode 100644 src/main/java/de/guntram/mcmod/easiervillagertrading/mixins/MerchantScreenMixin.java
 create mode 100644 src/main/resources/assets/easiervillagertrading/lang/en_US.lang
 create mode 100644 src/main/resources/assets/easiervillagertrading/lang/en_us.json
 create mode 100644 src/main/resources/fabric.mod.json
 create mode 100644 src/main/resources/logo.png
 delete mode 100644 src/main/resources/mcmod.info
 create mode 100644 src/main/resources/mixins.easiervillagertrading.json
 create mode 100644 src/main/resources/pack.mcmeta
 create mode 100644 src/main/resources/pack.png
bshuler@Omen:/mnt/c/Users/BertS/code/freshtest/EasierVillagerTrading$ gradle build

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/c/Users/BertS/code/freshtest/EasierVillagerTrading/build.gradle' line: 2

* What went wrong:
Plugin [id: 'fabric-loom', version: '0.2.5-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/4.4.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (snapshot plugin versions are not supported)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Pull request closed without merging**
